# Generated by Django 5.2.3 on 2025-08-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseAMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses_amp', to='bibles.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='VerseASV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses_asv', to='bibles.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='VerseNIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.IntegerField()),
                ('text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses_niv', to='bibles.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'verse')},
            },
        ),
    ]
