# Generated by Django 5.2.3 on 2025-09-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_video_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
                ('sermon_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_published', '-date_added']},
        ),
        migrations.AlterField(
            model_name='video',
            name='preacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='videos', to='sermons.preacher'),
        ),
    ]
