# Generated by Django 5.2.3 on 2025-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
