# Generated by Django 5.2.3 on 2025-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
