# Generated by Django 5.2.3 on 2025-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('verse', 'Bible Verse'), ('prayer', 'Prayer'), ('quote', 'Quote'), ('hymn', 'Hymn'), ('devotion', 'Devotion')], max_length=20)),
                ('preview_image', models.ImageField(upload_to='template_previews/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='template_backgrounds/')),
                ('html_template', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='templates', to='sharetemplates.templatetag')),
            ],
        ),
    ]
