# Generated by Django 5.2.3 on 2025-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='css_styles',
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='html_template',
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='sharetemplate',
            name='tags',
        ),
        migrations.AddField(
            model_name='sharetemplate',
            name='background',
            field=models.CharField(blank=True, help_text='Optional fallback background color (hex code)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sharetemplate',
            name='gradient_colors',
            field=models.JSONField(default=list, help_text='List of hex/rgb colors for gradient background'),
        ),
        migrations.AddField(
            model_name='sharetemplate',
            name='styles',
            field=models.JSONField(default=dict, help_text='Style definitions (lightRay1, verseText, referenceBadge, etc.)'),
        ),
        migrations.AddField(
            model_name='sharetemplate',
            name='text_color',
            field=models.CharField(default=1, help_text='Text color (hex code)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sharetemplate',
            name='name',
            field=models.CharField(help_text="Template name (e.g., 'Heavenly Light')", max_length=100),
        ),
        migrations.AlterField(
            model_name='sharetemplate',
            name='template_type',
            field=models.CharField(choices=[('verse', 'Bible Verse'), ('prayer', 'Prayer'), ('quote', 'Quote'), ('hymn', 'Hymn'), ('devotion', 'Devotion')], help_text='Type of template', max_length=10),
        ),
    ]
