# Generated by Django 5.2.3 on 2025-07-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_deleted_note_idx_notes_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='client_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
