# Generated by Django 5.2.3 on 2025-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_client_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='client_last_modified',
            field=models.TextField(blank=True, null=True),
        ),
    ]
