# Generated by Django 5.2.3 on 2025-07-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('theme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, unique=True)),
                ('theme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('scripture', models.CharField(max_length=100)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_readings', to='devotion.month')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyFamilyDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_verse_text', models.TextField()),
                ('bible_verse_reference', models.CharField(max_length=255)),
                ('devotion', models.TextField()),
                ('reflection_question_1', models.TextField(blank=True, null=True)),
                ('reflection_question_2', models.TextField(blank=True, null=True)),
                ('reflection_question_3', models.TextField(blank=True, null=True)),
                ('prayer', models.TextField()),
                ('family_challenge', models.TextField(blank=True, null=True)),
                ('devotional_date', models.DateField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_theme', to='devotion.dailyreading')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_theme', to='devotion.month')),
            ],
            options={
                'verbose_name': 'Daily Family Devotional',
                'verbose_name_plural': 'Daily Family Devotionals',
                'ordering': ['-devotional_date'],
            },
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='devotion.year'),
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_devotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='devotion.month')),
            ],
        ),
    ]
