# Generated by Django 5.2.3 on 2025-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyfamilydevotional',
            index=models.Index(fields=['devotional_date'], name='devotion_da_devotio_00129e_idx'),
        ),
    ]
