# Generated by Django 5.2.3 on 2025-07-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_number', models.PositiveIntegerField(unique=True)),
                ('prayer_category', models.CharField(max_length=100)),
                ('prayer', models.TextField()),
                ('prayer_scripture', models.CharField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prayer_number'],
            },
        ),
    ]
