# Generated by Django 5.2.3 on 2025-07-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_number',
        ),
    ]
