# Generated by Django 5.2.3 on 2025-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_alter_prayer_options_remove_prayer_prayer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
