# Generated by Django 5.2.3 on 2025-08-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_prayer_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prayer',
            old_name='draft',
            new_name='publish',
        ),
    ]
