# Generated by Django 5.2.3 on 2025-07-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('has_chorus', models.BooleanField(default=False)),
                ('chorus', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanza_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanzas', to='hymns.hymn')),
            ],
            options={
                'ordering': ['stanza_number'],
                'unique_together': {('hymn', 'stanza_number')},
            },
        ),
    ]
