# Generated by Django 5.2.3 on 2025-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
