# Generated by Django 5.2.3 on 2025-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0002_hymn_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='copyright',
            field=models.CharField(default='Public domain', max_length=255),
        ),
        migrations.AddField(
            model_name='hymn',
            name='scripture_references',
            field=models.TextField(blank=True, help_text='Comma-separated or JSON list of scripture references', null=True),
        ),
        migrations.AddField(
            model_name='hymn',
            name='source',
            field=models.CharField(default='hymnary.org', max_length=255),
        ),
    ]
